FROM node:16.16.0-alpine
WORKDIR /usr/src/app

# # Install create-react-app.
# RUN npm install -g create-react-app

# # Create a Reac application.
# WORKDIR /usr/src/app
# RUN npx create-react-app .

# # Run the Reac application.
# EXPOSE 3000
# CMD ["npm", "start"]