version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    image: react-learn
    container_name: react-learn
    volumes:
      - ./app:/usr/src/app:delegated
      # - /usr/src/app/node_modules
    command: sh -c "cd /usr/src/app && npm start"
    ports:
      - "3001:3000"
    tty: true
    stdin_open: true